### ISSUE TITLE
Fails to initialize 

### ISSUE THREAD

**Issue by p9a3** [EnhancedRadioDevices/LoRaChat#1]
Welcome to LoRaChat
SX1276 Failure: init failed.
Check hardware connections. Halting program.

I've now built multiple boards with Arduino Uno's and hamshield. Loaded LoraChat. They all work great, when they work. Takes a dozen or so bootups before the chip initializes. Something is wrong with the base code, but then again, it does work intermittently.. Not sure why, or what the best solution may be... Any help?

**Comment by spaceneedle** [comment]
Hello p9a3:

I am sorry for the trouble you are having. We found out that it is always best to perform a reset on the radio chip before starting any communication. This is actually common practice for most Semtech hardware, including the Adafruit Feathers. Place this code right before the init function. I will be updating the code on here soon as its needed to properly use the hardware.

pinMode(3,OUTPUT);
digitalWrite(3, LOW);
delay(10);
digitalWrite(3, HIGH);
delay(10);

Please confirm that this works.

**Comment by p9a3** [comment]
The added code has corrected the problem on the boards I've been experimenting with. Thanks.

**Comment by p9a3** [comment]
Can I just say, that this is killer stuff! I managed to pull off a 1 watt transmission from a dense urban center (major city in SoCal), and reached out in both directions 8 miles! We’re talking some absurd obstacles to overcome here. Multiple freeways, dozens of high rise concrete/glass buildings, and homes/tress, etc... The spread factor was set to 12, and the stations were receiving all msgs at/around -136 with a S/N ratio of -13. I used filters and some other ham tricks to pull off, but PLEASE continue to update code with some sort of store/forward, or repeat functionality. One of these on a mountaintop here could run off a solar panel, and provide text msg’ing for a quarter of California. Great work!
